// Generated by purs version 0.13.6
"use strict";
let Data_Semigroup = require("../Data.Semigroup/index.js");
let Data_Units = require("../Data.Units/index.js");
let Data_Units_SI = require("../Data.Units.SI/index.js");
let rpm = Data_Units.makeNonStandard("rpm")("rpm")(1.0 / 60.0)(Data_Units.power(Data_Units_SI.second)(-1.0));
let psi = Data_Units.makeNonStandard("psi")("psi")(6894757.0)(Data_Units.divideUnits(Data_Units_SI.gram)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.meter)(Data_Units.power(Data_Units_SI.second)(2.0))));
let pixel = Data_Units.makeStandard("pixel")("px");
let piece = Data_Units.makeStandard("piece")("piece");
let person = Data_Units.makeStandard("person")("person");
let mmHg = Data_Units.makeNonStandard("mmHg")("mmHg")(133322.387415)(Data_Units.divideUnits(Data_Units_SI.gram)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.meter)(Data_Units.power(Data_Units_SI.second)(2.0))));
let lbf = Data_Units.makeNonStandard("pound_force")("lbf")(4448.222)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.meter)(Data_Units.power(Data_Units_SI.second)(-2.0))));
let frame = Data_Units.makeStandard("frame")("frame");
let fortnight = Data_Units.makeNonStandard("fortnight")("fortnight")(14.0 * 24.0 * 3600.0)(Data_Units_SI.second);
let dot = Data_Units.makeStandard("dot")("dot");
let calorie = Data_Units.makeNonStandard("calorie")("cal")(4184.0)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Units.power(Data_Units_SI.second)(-2.0))));
let btu = Data_Units.makeNonStandard("BTU")("BTU")(1055055.85262)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Units.power(Data_Units_SI.second)(-2.0))));
let atm = Data_Units.makeNonStandard("atm")("atm")(1.01325e8)(Data_Units.divideUnits(Data_Units_SI.gram)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.meter)(Data_Units.power(Data_Units_SI.second)(2.0))));
module.exports = {
    calorie: calorie,
    btu: btu,
    lbf: lbf,
    rpm: rpm,
    fortnight: fortnight,
    mmHg: mmHg,
    psi: psi,
    atm: atm,
    pixel: pixel,
    dot: dot,
    frame: frame,
    piece: piece,
    person: person
};
