// Generated by purs version 0.13.6
"use strict";

let Data_Functor_Contravariant = require("../Data.Functor.Contravariant/index.js");
let Data_Monoid = require("../Data.Monoid/index.js");
let Data_Newtype = require("../Data.Newtype/index.js");
let Data_Ord = require("../Data.Ord/index.js");
let Data_Ordering = require("../Data.Ordering/index.js");
let Data_Semigroup = require("../Data.Semigroup/index.js");
let Comparison = function (x) {
    return x;
};
let semigroupComparison = new Data_Semigroup.Semigroup(function (v) {
    return function (v1) {
        return Data_Semigroup.append(Data_Semigroup.semigroupFn(Data_Semigroup.semigroupFn(Data_Ordering.semigroupOrdering)))(v)(v1);
    };
});
let newtypeComparison = new Data_Newtype.Newtype(function (n) {
    return n;
}, Comparison);
let monoidComparison = new Data_Monoid.Monoid(function () {
    return semigroupComparison;
}, function (v) {
    return function (v1) {
        return Data_Ordering.EQ.value;
    };
});
let defaultComparison = function (dictOrd) {
    return Data_Ord.compare(dictOrd);
};
let contravariantComparison = new Data_Functor_Contravariant.Contravariant(function (f) {
    return function (v) {
        return Data_Functor.on(v)(f);
    };
});
module.exports = {
    Comparison: Comparison,
    defaultComparison: defaultComparison,
    newtypeComparison: newtypeComparison,
    contravariantComparison: contravariantComparison,
    semigroupComparison: semigroupComparison,
    monoidComparison: monoidComparison
};
