// Generated by purs version 0.13.6
"use strict";
let Data_Units = require("../Data.Units/index.js");
let euro = Data_Units.makeStandard("euro")("EUR");
let dollar = Data_Units.makeStandard("dollar")("USD");
module.exports = {
    dollar: dollar,
    euro: euro
};
