// Generated by purs version 0.13.6
"use strict";
let Control_Monad_Reader_Trans = require("../Control.Monad.Reader.Trans/index.js");
let Data_Identity = require("../Data.Identity/index.js");
let Data_Newtype = require("../Data.Newtype/index.js");
let withReader = Control_Monad_Reader_Trans.withReaderT;
let runReader = function (v) {
    let $2 = Data_Newtype.unwrap(Data_Identity.newtypeIdentity);
    return function ($3) {
        return $2(v($3));
    };
};
let mapReader = function (f) {
    return Control_Monad_Reader_Trans.mapReaderT((function () {
        let $4 = Data_Newtype.unwrap(Data_Identity.newtypeIdentity);
        return function ($5) {
            return Data_Identity.Identity(f($4($5)));
        };
    })());
};
module.exports = {
    runReader: runReader,
    mapReader: mapReader,
    withReader: withReader
};
