// Generated by purs version 0.13.6
"use strict";
let Data_Bounded = require("../Data.Bounded/index.js");
let Data_Newtype = require("../Data.Newtype/index.js");
let Data_Ord = require("../Data.Ord/index.js");
let Data_Ordering = require("../Data.Ordering/index.js");
let Data_Show = require("../Data.Show/index.js");
let Down = function (x) {
    return x;
};
let showDown = function (dictShow) {
    return new Data_Show.Show(function (v) {
        return "(Down " + (Data_Show.show(dictShow)(v) + ")");
    });
};
let newtypeDown = new Data_Newtype.Newtype(function (n) {
    return n;
}, Down);
let eqDown = function (dictEq) {
    return dictEq;
};
let ordDown = function (dictOrd) {
    return new Data_Ord.Ord(function () {
        return eqDown(dictOrd.Eq0());
    }, function (v) {
        return function (v1) {
            return Data_Ordering.invert(Data_Ord.compare(dictOrd)(v)(v1));
        };
    });
};
let boundedDown = function (dictBounded) {
    return new Data_Bounded.Bounded(function () {
        return ordDown(dictBounded.Ord0());
    }, Data_Bounded.top(dictBounded), Data_Bounded.bottom(dictBounded));
};
module.exports = {
    Down: Down,
    newtypeDown: newtypeDown,
    eqDown: eqDown,
    ordDown: ordDown,
    boundedDown: boundedDown,
    showDown: showDown
};
