// Generated by purs version 0.13.6
"use strict";
let Data_Units = require("../Data.Units/index.js");
let Data_Units_SI = require("../Data.Units.SI/index.js");
let year = Data_Units.makeNonStandard("year")("year")(365.25 * 24.0 * 3600.0)(Data_Units_SI.second);
let week = Data_Units.makeNonStandard("week")("week")(7.0 * 24.0 * 3600.0)(Data_Units_SI.second);
let month = Data_Units.makeNonStandard("month")("month")((30.0 * 24.0 + 10.5) * 3600.0)(Data_Units_SI.second);
let minute = Data_Units.makeNonStandard("minute")("min")(60.0)(Data_Units_SI.second);
let hour = Data_Units.makeNonStandard("hour")("h")(3600.0)(Data_Units_SI.second);
let day = Data_Units.makeNonStandard("day")("d")(24.0 * 3600.0)(Data_Units_SI.second);
module.exports = {
    minute: minute,
    hour: hour,
    day: day,
    week: week,
    month: month,
    year: year
};
