// Generated by purs version 0.13.6
"use strict";
let Data_Units = require("../Data.Units/index.js");
let Data_Units_SI = require("../Data.Units.SI/index.js");
let yard = Data_Units.makeNonStandard("yard")("yd")(0.9144)(Data_Units_SI.meter);
let thou = Data_Units.makeNonStandard("thou")("thou")(2.54e-5)(Data_Units_SI.meter);
let pound = Data_Units.makeNonStandard("pound")("lb")(453.6)(Data_Units_SI.gram);
let ounce = Data_Units.makeNonStandard("ounce")("oz")(28.35)(Data_Units_SI.gram);
let mile = Data_Units.makeNonStandard("mile")("mi")(1609.344)(Data_Units_SI.meter);
let inch = Data_Units.makeNonStandard("inch")("in")(2.54e-2)(Data_Units_SI.meter);
let furlong = Data_Units.makeNonStandard("furlong")("furlong")(201.168)(Data_Units_SI.meter);
let foot = Data_Units.makeNonStandard("foot")("ft")(0.3048)(Data_Units_SI.meter);
module.exports = {
    inch: inch,
    foot: foot,
    yard: yard,
    mile: mile,
    ounce: ounce,
    pound: pound,
    thou: thou,
    furlong: furlong
};
