// Generated by purs version 0.13.6
"use strict";
let Data_Units = require("../Data.Units/index.js");
let percent = Data_Units.makeNonStandard("percent")("pct")(1.0e-2)(Data_Units.unity);
let partsPerTrillion = Data_Units.makeNonStandard("parts-per-trillion")("ppt")(1.0e-12)(Data_Units.unity);
let partsPerQuadrillion = Data_Units.makeNonStandard("parts-per-quadrillion")("ppq")(1.0e-15)(Data_Units.unity);
let partsPerMillion = Data_Units.makeNonStandard("parts-per-million")("ppm")(1.0e-6)(Data_Units.unity);
let partsPerBillion = Data_Units.makeNonStandard("parts-per-billion")("ppb")(1.0e-9)(Data_Units.unity);
module.exports = {
    percent: percent,
    partsPerMillion: partsPerMillion,
    partsPerBillion: partsPerBillion,
    partsPerTrillion: partsPerTrillion,
    partsPerQuadrillion: partsPerQuadrillion
};
