// Generated by purs version 0.13.6
"use strict";
let Data_Units = require("../Data.Units/index.js");
let second = Data_Units.makeStandard("second")("s");
let mole = Data_Units.makeStandard("mole")("mol");
let meter = Data_Units.makeStandard("meter")("m");
let kelvin = Data_Units.makeStandard("kelvin")("K");
let gram = Data_Units.makeStandard("gram")("g");
let kilogram = Data_Units.kilo(gram);
let candela = Data_Units.makeStandard("candela")("cd");
let ampere = Data_Units.makeStandard("ampere")("A");
module.exports = {
    meter: meter,
    kilogram: kilogram,
    second: second,
    gram: gram,
    ampere: ampere,
    mole: mole,
    kelvin: kelvin,
    candela: candela
};
