// Generated by purs version 0.13.6
"use strict";
let MonadTrans = function (lift) {
    this.lift = lift;
};
let lift = function (dict) {
    return dict.lift;
};
module.exports = {
    lift: lift,
    MonadTrans: MonadTrans
};
