// Generated by purs version 0.13.6
"use strict";
let Data_Semigroup = require("../Data.Semigroup/index.js");
let Data_Units = require("../Data.Units/index.js");
let Data_Units_SI = require("../Data.Units.SI/index.js");


let tonne = Data_Units.makeNonStandard("tonne")("ton")(1000000.0)(Data_Units_SI.gram);
let liter = Data_Units.makeNonStandard("liter")("L")(1.0e-3)(Data_Units.power(Data_Units_SI.meter)(3.0));
let hectare = Data_Units.makeNonStandard("hectare")("ha")(10000.0)(Data_Units.power(Data_Units_SI.meter)(2.0));
let electronvolt = Data_Units.makeNonStandard("electronvolt")("eV")(1.60217653e-16)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Units.power(Data_Units_SI.second)(2.0))));
let degree = Data_Units.makeNonStandard("degree")("\xb0")(Math.PI / 180.0)(Data_Units.unity);
let bel = Data_Units.makeStandard("bel")("bel");
let barn = Data_Units.makeNonStandard("barn")("barn")(1.0e-28)(Data_Units.power(Data_Units_SI.meter)(2.0));
let bar = Data_Units.makeNonStandard("bar")("bar")(1.0e8)(Data_Units.divideUnits(Data_Units_SI.gram)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.meter)(Data_Units.power(Data_Units_SI.second)(2.0))));
let astronomicalUnit = Data_Units.makeNonStandard("astronomical unit")("AU")(1.495978707e11)(Data_Units_SI.meter);
let angstrom = Data_Units.makeNonStandard("\xc5ngstr\xf6m")("\xc5")(1.0e-10)(Data_Units_SI.meter);
module.exports = {
    degree: degree,
    hectare: hectare,
    liter: liter,
    tonne: tonne,
    electronvolt: electronvolt,
    bel: bel,
    astronomicalUnit: astronomicalUnit,
    bar: bar,
    angstrom: angstrom,
    barn: barn
};
