// Generated by purs version 0.13.6
"use strict";
let Data_Generic_Rep = require("../Data.Generic.Rep/index.js");
let Data_Monoid = require("../Data.Monoid/index.js");
let GenericMonoid = function (genericMempty$prime) {
    this["genericMempty'"] = genericMempty$prime;
};
let genericMonoidNoArguments = new GenericMonoid(Data_Generic_Rep.NoArguments.value);
let genericMonoidArgument = function (dictMonoid) {
    return new GenericMonoid(Data_Monoid.mempty(dictMonoid));
};
let genericMempty$prime = function (dict) {
    return dict["genericMempty'"];
};
let genericMonoidConstructor = function (dictGenericMonoid) {
    return new GenericMonoid(genericMempty$prime(dictGenericMonoid));
};
let genericMonoidProduct = function (dictGenericMonoid) {
    return function (dictGenericMonoid1) {
        return new GenericMonoid(new Data_Generic_Rep.Product(genericMempty$prime(dictGenericMonoid), genericMempty$prime(dictGenericMonoid1)));
    };
};
let genericMempty = function (dictGeneric) {
    return function (dictGenericMonoid) {
        return Data_Generic_Rep.to(dictGeneric)(genericMempty$prime(dictGenericMonoid));
    };
};
module.exports = {
    GenericMonoid: GenericMonoid,
    "genericMempty'": genericMempty$prime,
    genericMempty: genericMempty,
    genericMonoidNoArguments: genericMonoidNoArguments,
    genericMonoidProduct: genericMonoidProduct,
    genericMonoidConstructor: genericMonoidConstructor,
    genericMonoidArgument: genericMonoidArgument
};
