// Generated by purs version 0.13.6
"use strict";
let $foreign = require("./foreign.js");
let poke = function (dictPartial) {
    return $foreign.pokeImpl;
};
let peek = function (dictPartial) {
    return $foreign.peekImpl;
};
module.exports = {
    peek: peek,
    poke: poke
};
