// Generated by purs version 0.13.6
"use strict";
let Data_Units = require("../Data.Units/index.js");
let Data_Units_SI = require("../Data.Units.SI/index.js");
let parsec = Data_Units.makeNonStandard("parsec")("parsec")(3.085677581e16)(Data_Units_SI.meter);
let lightyear = Data_Units.makeNonStandard("lightyear")("ly")(9.4607304725808e15)(Data_Units_SI.meter);
module.exports = {
    parsec: parsec,
    lightyear: lightyear
};
