// Generated by purs version 0.13.6
"use strict";
let $foreign = require("./foreign.js");
let Data_Functor = require("../Data.Functor/index.js");
let Effect = require("../Effect/index.js");
let modify = function (f) {
    return $foreign["modify'"](function (s) {
        let s$prime = f(s);
        return {
            state: s$prime,
            value: s$prime
        };
    });
};
let modify_ = function (f) {
    return function (s) {
        return Data_Functor._void(Effect.functorEffect)(modify(f)(s));
    };
};
module.exports = {
    modify: modify,
    modify_: modify_,
    "new": $foreign["new"],
    read: $foreign.read,
    "modify'": $foreign["modify'"],
    write: $foreign.write
};
