// Generated by purs version 0.13.6
"use strict";
let Data_Semigroup = require("../Data.Semigroup/index.js");
let Data_Units = require("../Data.Units/index.js");
let Data_Units_SI = require("../Data.Units.SI/index.js");
let weber = Data_Units.makeNonStandard("weber")("Wb")(1000.0)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units.power(Data_Units_SI.second)(2.0))(Data_Units_SI.ampere))));
let watt = Data_Units.makeNonStandard("watt")("W")(1000.0)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Units.power(Data_Units_SI.second)(3.0))));
let volt = Data_Units.makeNonStandard("volt")("V")(1000.0)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units.power(Data_Units_SI.second)(3.0))(Data_Units_SI.ampere))));
let tesla = Data_Units.makeNonStandard("tesla")("T")(1000.0)(Data_Units.divideUnits(Data_Units_SI.gram)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units.power(Data_Units_SI.second)(2.0))(Data_Units_SI.ampere)));
let steradian = Data_Units.makeNonStandard("steradian")("sr")(1.0)(Data_Units.unity);
let sievert = Data_Units.makeNonStandard("sievert")("Sv")(1.0)(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Units.power(Data_Units_SI.second)(2.0)));
let siemens = Data_Units.makeNonStandard("siemens")("S")(1.0e-3)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units.power(Data_Units_SI.second)(3.0))(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.ampere)(2.0))(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Units.power(Data_Units_SI.meter)(2.0)))));
let radian = Data_Units.makeNonStandard("radian")("rad")(1.0)(Data_Units.unity);
let pascal = Data_Units.makeNonStandard("pascal")("Pa")(1000.0)(Data_Units.divideUnits(Data_Units_SI.gram)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.meter)(Data_Units.power(Data_Units_SI.second)(2.0))));
let ohm = Data_Units.makeNonStandard("ohm")("\u03a9")(1000.0)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units.power(Data_Units_SI.second)(3.0))(Data_Units.power(Data_Units_SI.ampere)(2.0)))));
let newton = Data_Units.makeNonStandard("newton")("N")(1000.0)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Units.divideUnits(Data_Units_SI.meter)(Data_Units.power(Data_Units_SI.second)(2.0))));
let lux = Data_Units.makeNonStandard("lux")("lx")(1.0)(Data_Units.divideUnits(Data_Units_SI.candela)(Data_Units.power(Data_Units_SI.meter)(2.0)));
let lumen = Data_Units.makeNonStandard("lumen")("lm")(1.0)(Data_Units_SI.candela);
let katal = Data_Units.makeNonStandard("katal")("kat")(1.0)(Data_Units.divideUnits(Data_Units_SI.mole)(Data_Units_SI.second));
let joule = Data_Units.makeNonStandard("joule")("J")(1000.0)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Units.power(Data_Units_SI.second)(2.0))));
let hertz = Data_Units.makeNonStandard("hertz")("Hz")(1.0)(Data_Units.divideUnits(Data_Units.unity)(Data_Units_SI.second));
let henry = Data_Units.makeNonStandard("henry")("H")(1000.0)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.gram)(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units.power(Data_Units_SI.second)(2.0))(Data_Units.power(Data_Units_SI.ampere)(2.0)))));
let gray = Data_Units.makeNonStandard("gray")("Gy")(1.0)(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.meter)(2.0))(Data_Units.power(Data_Units_SI.second)(2.0)));
let farad = Data_Units.makeNonStandard("farad")("F")(1.0e-3)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units.power(Data_Units_SI.second)(4.0))(Data_Units.divideUnits(Data_Units.power(Data_Units_SI.ampere)(2.0))(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units.power(Data_Units_SI.gram)(1.0))(Data_Units.power(Data_Units_SI.meter)(2.0)))));
let coulomb = Data_Units.makeNonStandard("coulomb")("C")(1.0)(Data_Semigroup.append(Data_Units.semigroupDerivedUnit)(Data_Units_SI.ampere)(Data_Units_SI.second));
let becquerel = Data_Units.makeNonStandard("becquerel")("Bq")(1.0)(Data_Units.power(Data_Units_SI.second)(-1.0));
module.exports = {
    radian: radian,
    steradian: steradian,
    hertz: hertz,
    newton: newton,
    pascal: pascal,
    joule: joule,
    watt: watt,
    coulomb: coulomb,
    volt: volt,
    farad: farad,
    ohm: ohm,
    siemens: siemens,
    weber: weber,
    tesla: tesla,
    henry: henry,
    lumen: lumen,
    lux: lux,
    becquerel: becquerel,
    gray: gray,
    sievert: sievert,
    katal: katal
};
